.TH PWD 1
.SH NAME
pwd \- working directory name
.SH SYNOPSIS
.B pwd
.SH DESCRIPTION
.I Pwd\^
prints the pathname of the working (current) directory.
.SH "SEE ALSO"
cd(1).
.SH DIAGNOSTICS
.B "Cannot open .."
and
.B "Read error in .."
indicate possible file system trouble.  These messages should be
referred to a system programming counselor.
.\"	@(#)pwd.1	1.3	
