.TH SLEEP 1 
.SH NAME
sleep \- suspend execution for an interval
.SH SYNOPSIS
.B sleep
time
.SH DESCRIPTION
.I Sleep\^
suspends execution for
.I time\^
seconds.
It is used to execute a command
after a certain amount of time as in:
.PP
.RS 5
.B "(sleep 105; \fIcommand\fP\^)&"
.PP
.RE
or to execute a command under specified conditions, as in:
.PP
.RS 5
.B "while true"
.RE
.br
.RS 5
.B "do"
.br
.RE
.RS 10
\fIcommand\fP
.br
.RE
.RS 10
.B "sleep 37"
.br
.RE
.RS 5
.B done
.RE
.SH "SEE ALSO"
alarm(2), sleep(3C).
.SH BUGS
.I Time\^
must be less than 65536 seconds.
.\"	@(#)sleep.1	1.3	
