.TH WAIT 1 
.SH NAME
wait \- await completion of process
.SH SYNOPSIS
.B wait
.SH DESCRIPTION
Wait until all processes started with
.B &
have completed,
and report on abnormal terminations.
.PP
Because the
.IR  wait (2)
system call
must be executed in the parent process,
the shell itself executes
.IR wait ,
without creating a new process.
.SH "SEE ALSO"
sh(1).
.SH BUGS
This command cannot wait for processes of a 3-or-more-stage
pipeline that are not children of the shell.
.\"	@(#)wait.1	1.3	
