.TH INTRO 5
.SH NAME
intro \- introduction to miscellaneous facilities
.SH DESCRIPTION
This section describes facilities such as formatting
documentation and setting the terminal environment.
It also contains descriptions of various character set
tables, flag values, and user-accessible data types.
.\"	@(#)intro.5	1.3	
